### PR TITLE
const generics

### PR DESCRIPTION
**Pull request by burrbull**

### CODE REVIEW

**Review by eldruin — COMMENTED** [review]
Looks great to me, thanks! Only the MSRV in CI needs to be updated as well.

**Comment by thalesfragoso** [comment]
I would hold this just a little longer, because it's a very high MSRV (latest stable) and a lot of HALs depend on this crate.

**Comment by burrbull** [comment]
> I would hold this just a little longer, because it's a very high MSRV (latest stable) and a lot of HALs depend on this crate.
> 
> We might want to release #13 first, depending on how long it takes to be finished.

That's why I've rebased on #13 and that's why I suggest to increase major version.

And how long to wait? I've been waiting for 3 years to get rid of `GenericArray`'s.

**Comment by korken89** [comment]
I would also like to see this merged and released soon

**Comment by korken89** [comment]
Ping @thalesfragoso

**Comment by thalesfragoso** [comment]
Ok, I think we should go forward with const-generics now, but now this PR depends on #13, which isn't complete yet due to missing docs.

**Comment by korken89** [comment]
Hi, one impl send to be missing:

`WriteTarget for [MaybeUninit<T>; N]`

**Comment by burrbull** [comment]
> WriteTarget for [MaybeUninit<T>; N]

```
error[E0119]: conflicting implementations of trait `WriteTarget` for type `[core::mem::MaybeUninit<_>; _]`
   --> src/lib.rs:214:1
    |
206 | unsafe impl<T: WriteTarget, const N: usize> WriteTarget for [T; N] {
    | ------------------------------------------------------------------ first implementation here
...
214 | unsafe impl<T: WriteTarget, const N: usize> WriteTarget for [MaybeUninit<T>; N] {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ conflicting implementation for `[core::mem::MaybeUninit<_>; _]`
```

**Comment by korken89** [comment]
Ahh it was already capped by the array, awesome!

**Comment by andrewgazelka** [comment]
@burrbull you might want to rebase on #19, which is my copy of #13 but with documentation.

**Comment by burrbull** [comment]
Done

**Review by eldruin — APPROVED** [review]
Awesome, thank you!
bors r+

**Pull request merged**
