### PR TITLE
Add and document a MSRV of 1.37.0

### PR DESCRIPTION
**Pull request by therealprof**
Signed-off-by: Daniel Egger <daniel@eggers-club.de>

### CODE REVIEW

**Comment by therealprof** [comment]
bors try

**Comment by therealprof** [comment]
bors r? @eldruin

**Comment by thalesfragoso** [comment]
Hmm, why not 1.36 ?

**Comment by therealprof** [comment]
Because 1.37.0 is the oldest compiler I have lying around so I have been able to confirm that it actually works with that version apriori. 😅

I'm not a big fan of going nuts by supporting super old Rust versions but if you would like to re-PR this change with 1.36.0 that'd be okay for me.

**Comment by thalesfragoso** [comment]
1.37 is totally fine :)
I just asked because I thought I might have missed something.

**Review by eldruin — APPROVED** [review]
Looks good to me.

bors r+

**Pull request merged**
